version: "3.9"

services:
  # Backend ASP.NET Core
  backend:
    image: sistema-venta-backend:latest
    container_name: sistema-venta-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__cadenaSQL=Server=sqlserver;Database=BDDERMACORE;User=sa;Password=YourStrongPassword123;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - app_network

  # Frontend Angular + NGINX
  frontend:
    image: sistema-venta-frontend:latest
    container_name: sistema-venta-frontend
    build:
      context: ./AppSistemaVenta
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
      - ./database/init.sql:/init.sql
    networks:
      - app_network

volumes:
  sqlvolume:

networks:
  app_network:
    driver: bridge

